services:
    plex-server:
        hostname: plex-server
        container_name: plex-server
        image: linuxserver/plex:arm64v8-latest
        environment:
        - PUID=1000
        - PGID=1000
        - VERSION=docker
        - PLEX_CLAIM=
        ports:
        - 32400:32400
        - 1900:1900/udp
        - 3005:3005
#        - 5353:5353/udp
        - 8324:8324
        - 32410:32410/udp
        - 32412:32412/udp
        - 32413:32413/udp
        - 32414:32414/udp
        - 32469:32469
        restart: unless-stopped
    filebrowser:
        image: filebrowser/filebrowser
        ports:
        - 8080:80
    vpn:
        image: qmcgaw/gluetun
        container_name: vpn
        cap_add:
        - NET_ADMIN
        environment:
        - VPN_SERVICE_PROVIDER=mullvad
        - VPN_TYPE=openvpn
        - FIREWALL_INPUT_PORTS=9091 # transmission ui
        ports:
        - 9091:9091 # transmission ui
    transmission:
        image: linuxserver/transmission:arm64v8-latest
        network_mode: "service:vpn"
