services:
    plex-server:
        volumes:
        - ~/Downloads/media/plex/config:/config
        - ~/Downloads/media/:/plex-libraries
    filebrowser:
        volumes:
        - ~/Downloads/media:/srv
    vpn:
        environment:
        - OPENVPN_USER=
        - SERVER_CITIES=
    transmission:
        volumes:
        - ~/Downloads/media/transmission/downloads:/downloads
        - ~/Downloads/media/transmission/watch:/watch
        - ~/Downloads/media/transmission/config:/config